name: Continuous Delivery

# on:
#   release:
#     types: [published]
#   push:
#     branches: [master]
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy-dev-app:
    name: deploy the DEV app
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/deploy-app.yml
    with:
      env: dev
    secrets:
      slack_token: ${{ secrets.DEV_SLACK_TOKEN }}
      slack_signing_secret: ${{ secrets.DEV_SLACK_SIGNING_SECRET }}
      slack_channel: ${{ secrets.DEV_SLACK_CHANNEL }}
      org_webhook_secret: ${{ secrets.ORG_WEBHOOK_SECRET }}
      org_private_key: ${{ secrets.ORG_PRIVATE_KEY }}
      org_app_id: ${{ secrets.ORG_APP_ID }}

  deploy-prod-app:
    name: deploy the PROD app
    if: github.event_name == 'release'
    uses: ./.github/workflows/deploy-app.yml
    with:
      env: prod
    secrets:
      slack_token: ${{ secrets.PROD_SLACK_TOKEN }}
      slack_signing_secret: ${{ secrets.PROD_SLACK_SIGNING_SECRET }}
      slack_channel: ${{ secrets.PROD_SLACK_CHANNEL }}
      org_webhook_secret: ${{ secrets.ORG_WEBHOOK_SECRET }}
      org_private_key: ${{ secrets.ORG_PRIVATE_KEY }}
      org_app_id: ${{ secrets.ORG_APP_ID }}
